package Models;

public enum Permission {
        // Permissions for Cashier
        GENERATE_PRINTABLE_BILL,
        RECEIVE_ALERTS_IF_ITEM_NOT_EXIST_OR_OUT_OF_STOCK,
        VIEW_BILLS_AND_TOTAL_FOR_CURRENT_DAY,

        // Permissions for Manager
        OVERSEE_SALES_PERFORMANCE,
        SUPPLY_SECTOR_WITH_NEEDED_ITEMS,
        ENTER_NEW_ITEM_CATEGORIES,
        ADD_ITEMS_TO_STOCK,
        MONITOR_CASHIER_PERFORMANCE,
        MANAGE_EMPLOYEES,
        GENERATE_TOTAL_COST_INCOME,
        ACCESS_STATISTICS_ABOUT_SOLD_AND_PURCHASED_ITEMS,
}
